twist_mux:
  ros__parameters:
    topics:
      joy: # What even is this?
        topic   : joy_teleop/cmd_vel
        timeout : 0.5
        priority: 10
      bt_joy:
        topic   : bluetooth_teleop/cmd_vel
        timeout : 0.5
        priority: 9
      interactive_marker: # Same here, what is this used for?
        topic   : twist_marker_server/cmd_vel
        timeout : 0.5
        priority: 8
      external:
        topic   : cmd_vel
        timeout : 0.5
        priority: 1
    locks:
      e_stop:
        topic   : e_stop
        timeout : 0.0
        priority: 255